name: Python application CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: club
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Wait for PostgreSQL to become available
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL to become available..."
            sleep 2
          done
        env:
          PGPASSWORD: password
      - name: Run migrations (optional)
        run: |

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/club
        run: |
          pytest